### PR TITLE
add url converter

### PR DESCRIPTION
**Pull request by katout**
We want a way to convert url for firebase storage.

e.g.

```
void main() {
  CacheManager.convertUrl = convertUrl;
  runApp(new MyApp());
}

Future<String> convertUrl(String url) async {
  String newUrl = await FirebaseStorage.instance
      .ref()
      .child(url)
      .getDownloadURL() as String;
  return newUrl;
}

```

### CODE REVIEW

**Comment by ykphuah** [comment]
Thanks for this! The only cache image that supports Firebase Storage doesn't allow me to do zoom, and vice versa, until I found this. Hope to get merged in so I can remove my dependency_overrides

**Comment by katout** [comment]
@renefloor Do you think this?

**Comment by renefloor** [comment]
@katout I'm definitely willing to merge this, but I am almost done with a big rewrite of the library and thus also the API. I will add this in the new structure. The new structure should also be more maintainable and more easy to add features without it becoming a mess. You can see the progress here: https://github.com/renefloor/flutter_cache_manager/tree/feature/seperation-of-functions

**Comment by renefloor** [comment]
Version `0.3.0-alpha.2` gives the option to customise the http getter, so you can convert the url in that method.

**Pull request closed without merging**
