### PR TITLE
allow customizing how files are downloaded, not just the headers.

### PR DESCRIPTION
**Pull request by hpoul**
A small change to allow clients to customize download behavior, instead of using the defaul http.get() method.

My specific use case is that I have a NTLM Authentication, but can't just push in the (cookie) headers, because 1.) I want to catch the case when my session expires and I need to reauthenticate with the server. and 2.) I fetch images from different servers, which have different sessions but the same authentication.

Is this something you'd consider merging? I would also patch https://github.com/renefloor/flutter_cached_network_image to allow the same customization.

### CODE REVIEW

**Comment by The-Redhat** [comment]
Nice work. I also really need this for a project. 👍

**Comment by krwrang** [comment]
This would simplify my code too, as currently I have to check my tokens first for refreshing needs before I can let CachedNetworkImage do its thing.

**Comment by lifenautjoe** [comment]
Hi @renefloor , this would be great! Please take al look 🙏

**Comment by renefloor** [comment]
@hpoul I was working on a complete redesign of the library and the API, so that's why I didn't merge this pull request. I did use your idea in the new design though, so thanks for the pull request anyway. The new design should be much more flexible in the long run.
See this commit: https://github.com/renefloor/flutter_cache_manager/commit/f3d71e227981e39c1d75b707085fc9d5ad3241d7

I will publish a new alpha or beta build soon.

**Comment by lifenautjoe** [comment]
Awesome to hear Rene !

Looking forward to it.

**Comment by renefloor** [comment]
@lifenautjoe see version `0.3.0-alpha.2`. The readme of that release already gives a good direction on how to implement it.

**Comment by hpoul** [comment]
@renefloor thanks, i have since abstracted even more, because i migrated from http library to dio - would this be something worth looking at too? see https://github.com/AustrianApps/flutter_cache_manager/commit/7cca69da6d1491d945c7469189f132a2db4b04da

**Comment by renefloor** [comment]
@hpoul could be interesting, do you already have a use case for it?

**Comment by hpoul** [comment]
@renefloor yep, I have migrated away from the http package in favor of dio: https://github.com/flutterchina/dio/ - mostly because the default http library does not support multi value headers and I didn't want to patch it because it was such a hotly debated topic that i doubt it would ever get merged ( https://github.com/dart-lang/sdk/issues/21802 ) - and dio seems pretty good (at least API wise) and I've implemented NTLM authenticated based on dio interceptors.

**Comment by renefloor** [comment]
@hpoul I just implemented your suggestion, will release this soon: https://github.com/renefloor/flutter_cache_manager/commit/ea7ff1f2063398ee89e3b6512a23c0a78c6df911

**Pull request closed without merging**
