### PR TITLE
Update for Dart 2

### PR DESCRIPTION
**Pull request by Cretezy**
* Update dependencies
* Fix deprecations
* Update for Dart 2 syntax

### CODE REVIEW

**Comment by Cretezy** [comment]
In the meantime:

```
dependencies:
  flutter_cache_manager:
    git: https://github.com/Cretezy/flutter_cache_manager.git
```

**Comment by creativecreatorormaybenot** [comment]
I am wondering if @renefloor is still servicing these plugins.

**Comment by bartektartanus** [comment]
Can you please merge this pull request @renefloor  ?

**Comment by blackmenthor** [comment]
Yes, please merge this pull request because i can't use my forked version since the dependency with other libraries

**Pull request closed without merging**
